let monthMap=new Map();
for(let i=0;i<50;i++)
{
    a=Math.floor(Math.random()*12)+1;
    if(a==1)
    {
        monthMap.set("January",i);
    }
    if(a==2)
    {
        monthMap.set("February",i);
    }
    if(a==3)
    {
        monthMap.set("March",i);
    }
    if(a==4)
    {
        monthMap.set("April",i);
    }
    if(a==5)
    {
        monthMap.set("May",i);
    }
    if(a==6)
    {
        monthMap.set("June",i);
    }
    if(a==7)
    {
        monthMap.set("July",i);
    }
    if(a==8)
    {
        monthMap.set("August",i);
    }
    if(a==9)
    {
        monthMap.set("September",i);
    }
    if(a==10)
    {
        monthMap.set("October",i);
    }
    if(a==11)
    {
        monthMap.set("November",i);
    }
    if(a==12)
    {
        monthMap.set("December",i);
    }
}
console.log(monthMap);